service: myfirstproject
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
        - s3:*
        - ses:*
      Resource: '*'
            
          

plugins:
  - serverless-s3-sync
  - serverless-webpack

package: 
  individually: true
  

custom:
  tableName: my-player-points
  bucketName: my-company-my-project-us-east-1-20230224-1246c9d6debcba0fcfca0
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: UploadData

functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events:
      - http: 
          path: get-user/{ID}
          method: GET 
          cors: true
  getPlayerScore:
    handler: lambdas/endpoints/getPlayerScore.handler
    events:
      - http: 
          path: get-player-scrore/{ID}
          method: GET 
          cors: true
  createPlayerScore:
    handler: lambdas/endpoints/createPlayerScore.handler
    events:
      - http: 
          path: create-player-scrore/{ID}
          method: POST
          cors: true       

  createFile:
    handler: lambdas/endpoints/createFile.handler
    events:
      - http: 
          path: create-file/{fileName}
          method: POST
          cors: true     
  getFile:
    handler: lambdas/endpoints/getFile.handler
    events:
      - http: 
          path: get-file/{fileName}
          method: GET
          cors: true 

  sendEmail:
    handler: lambdas/endpoints/sendEmail.handler
    events:
      - http: 
          path: send-email
          method: POST
          cors: true         



resources:
  Resources:
    MyS3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:custom.bucketName}
    MyDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST



